#!/bin/bash

# lunarvim
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh) -y
npm i -g bash-language-server
dotnet tool install --global csharp-ls

# dotfiles
git clone https://github.com/hmanhng/dotfile.git ~/dotfiles && cd ~/dotfiles && ./install.sh
